### PR TITLE
Just a basic port to 1.7.10

### PR DESCRIPTION
**Pull request by ghost**
I just ported your mod to 1.7.10 and thought instead of releasing it as my own i should post a PR so that you know

### CODE REVIEW

**Comment by jmesserli** [comment]
@WARDOGSK93 thanks alot for your help! I'll make sure to look at it tonight or tomorrow :+1: 
you'll get credit of course ;)

**Comment by WARDOGSK93** [comment]
@jmesserli thanks for the fast reply

**Comment by jmesserli** [comment]
finally had the time to merge it, thanks again @WARDOGSK93 :)

**Comment by ghost** [comment]
Your welcome @jmesserli glad i could help / update the mod

**Pull request merged**
